"""Established non-startup product-company career catalog additions.

This catalog intentionally uses large public or long-running enterprise/product
companies and avoids startup-only source lists. These are discovery entries,
not verified ATS integrations. Entries are kept separate from
`COMPANY_CAREER_TARGETS` because active scraping still depends on a supported
public ATS endpoint being configured per employer.
"""

NON_STARTUP_PRODUCT_COMPANY_CAREER_PAGE_URLS = {
    '3M': 'https://www.google.com/search?q=3M+careers',
    'A. O. Smith': 'https://www.google.com/search?q=A.+O.+Smith+careers',
    'Abbott Laboratories': 'https://www.google.com/search?q=Abbott+Laboratories+careers',
    'AbbVie': 'https://www.google.com/search?q=AbbVie+careers',
    'Adobe Inc.': 'https://www.google.com/search?q=Adobe+Inc.+careers',
    'Advanced Micro Devices': 'https://www.google.com/search?q=Advanced+Micro+Devices+careers',
    'AES Corporation': 'https://www.google.com/search?q=AES+Corporation+careers',
    'Aflac': 'https://www.google.com/search?q=Aflac+careers',
    'Agilent Technologies': 'https://www.google.com/search?q=Agilent+Technologies+careers',
    'Air Products': 'https://www.google.com/search?q=Air+Products+careers',
    'Akamai Technologies': 'https://www.google.com/search?q=Akamai+Technologies+careers',
    'Albemarle Corporation': 'https://www.google.com/search?q=Albemarle+Corporation+careers',
    'Alexandria Real Estate Equities': 'https://www.google.com/search?q=Alexandria+Real+Estate+Equities+careers',
    'Align Technology': 'https://www.google.com/search?q=Align+Technology+careers',
    'Allegion': 'https://www.google.com/search?q=Allegion+careers',
    'Alliant Energy': 'https://www.google.com/search?q=Alliant+Energy+careers',
    'Allstate': 'https://www.google.com/search?q=Allstate+careers',
    'Alphabet Inc. (Class A)': 'https://www.google.com/search?q=Alphabet+Inc.+%28Class+A%29+careers',
    'Alphabet Inc. (Class C)': 'https://www.google.com/search?q=Alphabet+Inc.+%28Class+C%29+careers',
    'Altria': 'https://www.google.com/search?q=Altria+careers',
    'Amazon': 'https://www.google.com/search?q=Amazon+careers',
    'Amcor': 'https://www.google.com/search?q=Amcor+careers',
    'Ameren': 'https://www.google.com/search?q=Ameren+careers',
    'American Electric Power': 'https://www.google.com/search?q=American+Electric+Power+careers',
    'American International Group': 'https://www.google.com/search?q=American+International+Group+careers',
    'American Tower': 'https://www.google.com/search?q=American+Tower+careers',
    'American Water Works': 'https://www.google.com/search?q=American+Water+Works+careers',
    'Ameriprise Financial': 'https://www.google.com/search?q=Ameriprise+Financial+careers',
    'Ametek': 'https://www.google.com/search?q=Ametek+careers',
    'Amgen': 'https://www.google.com/search?q=Amgen+careers',
    'Amphenol': 'https://www.google.com/search?q=Amphenol+careers',
    'Analog Devices': 'https://www.google.com/search?q=Analog+Devices+careers',
    'Aon plc': 'https://www.google.com/search?q=Aon+plc+careers',
    'APA Corporation': 'https://www.google.com/search?q=APA+Corporation+careers',
    'Apollo Global Management': 'https://www.google.com/search?q=Apollo+Global+Management+careers',
    'Apple Inc.': 'https://www.google.com/search?q=Apple+Inc.+careers',
    'AppLovin': 'https://www.google.com/search?q=AppLovin+careers',
    'Aptiv': 'https://www.google.com/search?q=Aptiv+careers',
    'Arch Capital Group': 'https://www.google.com/search?q=Arch+Capital+Group+careers',
    'Archer Daniels Midland': 'https://www.google.com/search?q=Archer+Daniels+Midland+careers',
    'Ares Management': 'https://www.google.com/search?q=Ares+Management+careers',
    'Arthur J. Gallagher & Co.': 'https://www.google.com/search?q=Arthur+J.+Gallagher+%26+Co.+careers',
    'Assurant': 'https://www.google.com/search?q=Assurant+careers',
    'AT&T': 'https://www.google.com/search?q=AT%26T+careers',
    'Atmos Energy': 'https://www.google.com/search?q=Atmos+Energy+careers',
    'Automatic Data Processing': 'https://www.google.com/search?q=Automatic+Data+Processing+careers',
    'AutoZone': 'https://www.google.com/search?q=AutoZone+careers',
    'AvalonBay Communities': 'https://www.google.com/search?q=AvalonBay+Communities+careers',
    'Avery Dennison': 'https://www.google.com/search?q=Avery+Dennison+careers',
    'Axon Enterprise': 'https://www.google.com/search?q=Axon+Enterprise+careers',
    'Baker Hughes': 'https://www.google.com/search?q=Baker+Hughes+careers',
    'Ball Corporation': 'https://www.google.com/search?q=Ball+Corporation+careers',
    'Bank of America': 'https://www.google.com/search?q=Bank+of+America+careers',
    'Baxter International': 'https://www.google.com/search?q=Baxter+International+careers',
    'Becton Dickinson': 'https://www.google.com/search?q=Becton+Dickinson+careers',
    'Berkshire Hathaway': 'https://www.google.com/search?q=Berkshire+Hathaway+careers',
    'Best Buy': 'https://www.google.com/search?q=Best+Buy+careers',
    'Bio-Techne': 'https://www.google.com/search?q=Bio-Techne+careers',
    'Biogen': 'https://www.google.com/search?q=Biogen+careers',
    'BlackRock': 'https://www.google.com/search?q=BlackRock+careers',
    'Blackstone Inc.': 'https://www.google.com/search?q=Blackstone+Inc.+careers',
    'Block, Inc.': 'https://www.google.com/search?q=Block%2C+Inc.+careers',
    'BNY Mellon': 'https://www.google.com/search?q=BNY+Mellon+careers',
    'Booking Holdings': 'https://www.google.com/search?q=Booking+Holdings+careers',
    'Boston Scientific': 'https://www.google.com/search?q=Boston+Scientific+careers',
    'Broadridge Financial Solutions': 'https://www.google.com/search?q=Broadridge+Financial+Solutions+careers',
    'Brown & Brown': 'https://www.google.com/search?q=Brown+%26+Brown+careers',
    'Brown\u2013Forman': 'https://www.google.com/search?q=Brown%E2%80%93Forman+careers',
    'Builders FirstSource': 'https://www.google.com/search?q=Builders+FirstSource+careers',
    'Bunge Global': 'https://www.google.com/search?q=Bunge+Global+careers',
    'BXP, Inc.': 'https://www.google.com/search?q=BXP%2C+Inc.+careers',
    'C.H. Robinson': 'https://www.google.com/search?q=C.H.+Robinson+careers',
    'Cadence Design Systems': 'https://www.google.com/search?q=Cadence+Design+Systems+careers',
    'Camden Property Trust': 'https://www.google.com/search?q=Camden+Property+Trust+careers',
    'Cardinal Health': 'https://www.google.com/search?q=Cardinal+Health+careers',
    'Carnival Corporation': 'https://www.google.com/search?q=Carnival+Corporation+careers',
    'Carrier Global': 'https://www.google.com/search?q=Carrier+Global+careers',
    'Carvana': 'https://www.google.com/search?q=Carvana+careers',
    "Casey's": 'https://www.google.com/search?q=Casey%27s+careers',
    'Caterpillar Inc.': 'https://www.google.com/search?q=Caterpillar+Inc.+careers',
    'Cboe Global Markets': 'https://www.google.com/search?q=Cboe+Global+Markets+careers',
    'CBRE Group': 'https://www.google.com/search?q=CBRE+Group+careers',
    'CDW Corporation': 'https://www.google.com/search?q=CDW+Corporation+careers',
    'Cencora': 'https://www.google.com/search?q=Cencora+careers',
    'Centene Corporation': 'https://www.google.com/search?q=Centene+Corporation+careers',
    'CenterPoint Energy': 'https://www.google.com/search?q=CenterPoint+Energy+careers',
    'CF Industries': 'https://www.google.com/search?q=CF+Industries+careers',
    'Charles River Laboratories': 'https://www.google.com/search?q=Charles+River+Laboratories+careers',
    'Charles Schwab Corporation': 'https://www.google.com/search?q=Charles+Schwab+Corporation+careers',
    'Charter Communications': 'https://www.google.com/search?q=Charter+Communications+careers',
    'Chevron Corporation': 'https://www.google.com/search?q=Chevron+Corporation+careers',
    'Chipotle Mexican Grill': 'https://www.google.com/search?q=Chipotle+Mexican+Grill+careers',
    'Chubb Limited': 'https://www.google.com/search?q=Chubb+Limited+careers',
    'Church & Dwight': 'https://www.google.com/search?q=Church+%26+Dwight+careers',
    'Ciena': 'https://www.google.com/search?q=Ciena+careers',
    'Cigna': 'https://www.google.com/search?q=Cigna+careers',
    'Cincinnati Financial': 'https://www.google.com/search?q=Cincinnati+Financial+careers',
    'Cintas': 'https://www.google.com/search?q=Cintas+careers',
    'Citigroup': 'https://www.google.com/search?q=Citigroup+careers',
    'Citizens Financial Group': 'https://www.google.com/search?q=Citizens+Financial+Group+careers',
    'Clorox': 'https://www.google.com/search?q=Clorox+careers',
    'CME Group': 'https://www.google.com/search?q=CME+Group+careers',
    'CMS Energy': 'https://www.google.com/search?q=CMS+Energy+careers',
    'Coca-Cola Company (The)': 'https://www.google.com/search?q=Coca-Cola+Company+%28The%29+careers',
    'Coherent Corp.': 'https://www.google.com/search?q=Coherent+Corp.+careers',
    'Colgate-Palmolive': 'https://www.google.com/search?q=Colgate-Palmolive+careers',
    'Comcast': 'https://www.google.com/search?q=Comcast+careers',
    'Comfort Systems USA': 'https://www.google.com/search?q=Comfort+Systems+USA+careers',
    'ConocoPhillips': 'https://www.google.com/search?q=ConocoPhillips+careers',
    'Consolidated Edison': 'https://www.google.com/search?q=Consolidated+Edison+careers',
    'Constellation Brands': 'https://www.google.com/search?q=Constellation+Brands+careers',
    'Constellation Energy': 'https://www.google.com/search?q=Constellation+Energy+careers',
    'Cooper Companies (The)': 'https://www.google.com/search?q=Cooper+Companies+%28The%29+careers',
    'Copart': 'https://www.google.com/search?q=Copart+careers',
    'Corning Inc.': 'https://www.google.com/search?q=Corning+Inc.+careers',
    'Corpay': 'https://www.google.com/search?q=Corpay+careers',
    'Corteva': 'https://www.google.com/search?q=Corteva+careers',
    'CoStar Group': 'https://www.google.com/search?q=CoStar+Group+careers',
    'Costco': 'https://www.google.com/search?q=Costco+careers',
    'CRH plc': 'https://www.google.com/search?q=CRH+plc+careers',
    'Crown Castle': 'https://www.google.com/search?q=Crown+Castle+careers',
    'CSX Corporation': 'https://www.google.com/search?q=CSX+Corporation+careers',
    'Cummins': 'https://www.google.com/search?q=Cummins+careers',
    'CVS Health': 'https://www.google.com/search?q=CVS+Health+careers',
    'Danaher Corporation': 'https://www.google.com/search?q=Danaher+Corporation+careers',
    'Darden Restaurants': 'https://www.google.com/search?q=Darden+Restaurants+careers',
    'DaVita': 'https://www.google.com/search?q=DaVita+careers',
    'Deckers Brands': 'https://www.google.com/search?q=Deckers+Brands+careers',
    'Deere & Company': 'https://www.google.com/search?q=Deere+%26+Company+careers',
    'Delta Air Lines': 'https://www.google.com/search?q=Delta+Air+Lines+careers',
    'Devon Energy': 'https://www.google.com/search?q=Devon+Energy+careers',
    'Dexcom': 'https://www.google.com/search?q=Dexcom+careers',
    'Diamondback Energy': 'https://www.google.com/search?q=Diamondback+Energy+careers',
    'Digital Realty': 'https://www.google.com/search?q=Digital+Realty+careers',
    'Dollar General': 'https://www.google.com/search?q=Dollar+General+careers',
    'Dollar Tree': 'https://www.google.com/search?q=Dollar+Tree+careers',
    'Dominion Energy': 'https://www.google.com/search?q=Dominion+Energy+careers',
    "Domino's": 'https://www.google.com/search?q=Domino%27s+careers',
    'DoorDash': 'https://www.google.com/search?q=DoorDash+careers',
    'Dover Corporation': 'https://www.google.com/search?q=Dover+Corporation+careers',
    'Dow Inc.': 'https://www.google.com/search?q=Dow+Inc.+careers',
    'D. R. Horton': 'https://www.google.com/search?q=D.+R.+Horton+careers',
    'DTE Energy': 'https://www.google.com/search?q=DTE+Energy+careers',
    'Duke Energy': 'https://www.google.com/search?q=Duke+Energy+careers',
    'DuPont': 'https://www.google.com/search?q=DuPont+careers',
    'Eaton Corporation': 'https://www.google.com/search?q=Eaton+Corporation+careers',
    'eBay Inc.': 'https://www.google.com/search?q=eBay+Inc.+careers',
    'EchoStar': 'https://www.google.com/search?q=EchoStar+careers',
    'Ecolab': 'https://www.google.com/search?q=Ecolab+careers',
    'Edison International': 'https://www.google.com/search?q=Edison+International+careers',
    'Edwards Lifesciences': 'https://www.google.com/search?q=Edwards+Lifesciences+careers',
    'Electronic Arts': 'https://www.google.com/search?q=Electronic+Arts+careers',
    'Elevance Health': 'https://www.google.com/search?q=Elevance+Health+careers',
    'Emcor': 'https://www.google.com/search?q=Emcor+careers',
    'Emerson Electric': 'https://www.google.com/search?q=Emerson+Electric+careers',
    'Entergy': 'https://www.google.com/search?q=Entergy+careers',
    'EOG Resources': 'https://www.google.com/search?q=EOG+Resources+careers',
    'EQT Corporation': 'https://www.google.com/search?q=EQT+Corporation+careers',
    'Equifax': 'https://www.google.com/search?q=Equifax+careers',
    'Equity Residential': 'https://www.google.com/search?q=Equity+Residential+careers',
    'Erie Indemnity': 'https://www.google.com/search?q=Erie+Indemnity+careers',
    'Essex Property Trust': 'https://www.google.com/search?q=Essex+Property+Trust+careers',
    'Est\xe9e Lauder Companies (The)': 'https://www.google.com/search?q=Est%C3%A9e+Lauder+Companies+%28The%29+careers',
    'Everest Group': 'https://www.google.com/search?q=Everest+Group+careers',
    'Evergy': 'https://www.google.com/search?q=Evergy+careers',
    'Eversource Energy': 'https://www.google.com/search?q=Eversource+Energy+careers',
    'Exelon': 'https://www.google.com/search?q=Exelon+careers',
    'Expand Energy': 'https://www.google.com/search?q=Expand+Energy+careers',
    'Expedia Group': 'https://www.google.com/search?q=Expedia+Group+careers',
    'Expeditors International': 'https://www.google.com/search?q=Expeditors+International+careers',
    'Extra Space Storage': 'https://www.google.com/search?q=Extra+Space+Storage+careers',
    'ExxonMobil': 'https://www.google.com/search?q=ExxonMobil+careers',
    'F5, Inc.': 'https://www.google.com/search?q=F5%2C+Inc.+careers',
    'FactSet': 'https://www.google.com/search?q=FactSet+careers',
    'Fair Isaac': 'https://www.google.com/search?q=Fair+Isaac+careers',
    'Fastenal': 'https://www.google.com/search?q=Fastenal+careers',
    'Federal Realty Investment Trust': 'https://www.google.com/search?q=Federal+Realty+Investment+Trust+careers',
    'FedEx': 'https://www.google.com/search?q=FedEx+careers',
    'FedEx Freight': 'https://www.google.com/search?q=FedEx+Freight+careers',
    'Fidelity National Information Services': 'https://www.google.com/search?q=Fidelity+National+Information+Services+careers',
    'Fifth Third Bancorp': 'https://www.google.com/search?q=Fifth+Third+Bancorp+careers',
    'First Solar': 'https://www.google.com/search?q=First+Solar+careers',
    'FirstEnergy': 'https://www.google.com/search?q=FirstEnergy+careers',
    'Fiserv': 'https://www.google.com/search?q=Fiserv+careers',
    'Flex Ltd.': 'https://www.google.com/search?q=Flex+Ltd.+careers',
    'Ford Motor Company': 'https://www.google.com/search?q=Ford+Motor+Company+careers',
    'Fortive': 'https://www.google.com/search?q=Fortive+careers',
    'Fox Corporation (Class A)': 'https://www.google.com/search?q=Fox+Corporation+%28Class+A%29+careers',
    'Fox Corporation (Class B)': 'https://www.google.com/search?q=Fox+Corporation+%28Class+B%29+careers',
    'Franklin Resources': 'https://www.google.com/search?q=Franklin+Resources+careers',
    'Freeport-McMoRan': 'https://www.google.com/search?q=Freeport-McMoRan+careers',
    'Garmin': 'https://www.google.com/search?q=Garmin+careers',
    'Gartner': 'https://www.google.com/search?q=Gartner+careers',
    'GE HealthCare': 'https://www.google.com/search?q=GE+HealthCare+careers',
    'GE Vernova': 'https://www.google.com/search?q=GE+Vernova+careers',
    'Gen Digital': 'https://www.google.com/search?q=Gen+Digital+careers',
    'Generac': 'https://www.google.com/search?q=Generac+careers',
    'General Dynamics': 'https://www.google.com/search?q=General+Dynamics+careers',
    'General Mills': 'https://www.google.com/search?q=General+Mills+careers',
    'General Motors': 'https://www.google.com/search?q=General+Motors+careers',
    'Genuine Parts Company': 'https://www.google.com/search?q=Genuine+Parts+Company+careers',
    'Gilead Sciences': 'https://www.google.com/search?q=Gilead+Sciences+careers',
    'Global Payments': 'https://www.google.com/search?q=Global+Payments+careers',
    'Globe Life': 'https://www.google.com/search?q=Globe+Life+careers',
    'Halliburton': 'https://www.google.com/search?q=Halliburton+careers',
    'Hartford (The)': 'https://www.google.com/search?q=Hartford+%28The%29+careers',
    'Hasbro': 'https://www.google.com/search?q=Hasbro+careers',
    'HCA Healthcare': 'https://www.google.com/search?q=HCA+Healthcare+careers',
    'Healthpeak Properties': 'https://www.google.com/search?q=Healthpeak+Properties+careers',
    'Henry Schein': 'https://www.google.com/search?q=Henry+Schein+careers',
    'Hershey Company (The)': 'https://www.google.com/search?q=Hershey+Company+%28The%29+careers',
    'Hewlett Packard Enterprise': 'https://www.google.com/search?q=Hewlett+Packard+Enterprise+careers',
    'Hilton Worldwide': 'https://www.google.com/search?q=Hilton+Worldwide+careers',
    'Home Depot (The)': 'https://www.google.com/search?q=Home+Depot+%28The%29+careers',
    'Honeywell Aerospace': 'https://www.google.com/search?q=Honeywell+Aerospace+careers',
    'Honeywell Technologies': 'https://www.google.com/search?q=Honeywell+Technologies+careers',
    'Hormel Foods': 'https://www.google.com/search?q=Hormel+Foods+careers',
    'Host Hotels & Resorts': 'https://www.google.com/search?q=Host+Hotels+%26+Resorts+careers',
    'Howmet Aerospace': 'https://www.google.com/search?q=Howmet+Aerospace+careers',
    'HP Inc.': 'https://www.google.com/search?q=HP+Inc.+careers',
    'Hubbell Incorporated': 'https://www.google.com/search?q=Hubbell+Incorporated+careers',
    'Humana': 'https://www.google.com/search?q=Humana+careers',
    'Huntington Bancshares': 'https://www.google.com/search?q=Huntington+Bancshares+careers',
    'Huntington Ingalls Industries': 'https://www.google.com/search?q=Huntington+Ingalls+Industries+careers',
    'IDEX Corporation': 'https://www.google.com/search?q=IDEX+Corporation+careers',
    'Idexx Laboratories': 'https://www.google.com/search?q=Idexx+Laboratories+careers',
    'Illinois Tool Works': 'https://www.google.com/search?q=Illinois+Tool+Works+careers',
    'Incyte': 'https://www.google.com/search?q=Incyte+careers',
    'Ingersoll Rand': 'https://www.google.com/search?q=Ingersoll+Rand+careers',
    'Insulet Corporation': 'https://www.google.com/search?q=Insulet+Corporation+careers',
    'Interactive Brokers': 'https://www.google.com/search?q=Interactive+Brokers+careers',
    'Intercontinental Exchange': 'https://www.google.com/search?q=Intercontinental+Exchange+careers',
    'International Flavors & Fragrances': 'https://www.google.com/search?q=International+Flavors+%26+Fragrances+careers',
    'International Paper': 'https://www.google.com/search?q=International+Paper+careers',
    'Intuitive Surgical': 'https://www.google.com/search?q=Intuitive+Surgical+careers',
    'Invesco': 'https://www.google.com/search?q=Invesco+careers',
    'Invitation Homes': 'https://www.google.com/search?q=Invitation+Homes+careers',
    'IQVIA': 'https://www.google.com/search?q=IQVIA+careers',
    'Iron Mountain': 'https://www.google.com/search?q=Iron+Mountain+careers',
    'J.B. Hunt': 'https://www.google.com/search?q=J.B.+Hunt+careers',
    'Jabil': 'https://www.google.com/search?q=Jabil+careers',
    'Jack Henry & Associates': 'https://www.google.com/search?q=Jack+Henry+%26+Associates+careers',
    'Jacobs Solutions': 'https://www.google.com/search?q=Jacobs+Solutions+careers',
    'Johnson Controls': 'https://www.google.com/search?q=Johnson+Controls+careers',
    'Kenvue': 'https://www.google.com/search?q=Kenvue+careers',
    'Keurig Dr Pepper': 'https://www.google.com/search?q=Keurig+Dr+Pepper+careers',
    'KeyCorp': 'https://www.google.com/search?q=KeyCorp+careers',
    'Kimberly-Clark': 'https://www.google.com/search?q=Kimberly-Clark+careers',
    'Kimco Realty': 'https://www.google.com/search?q=Kimco+Realty+careers',
    'Kinder Morgan': 'https://www.google.com/search?q=Kinder+Morgan+careers',
    'KKR & Co.': 'https://www.google.com/search?q=KKR+%26+Co.+careers',
    'KLA Corporation': 'https://www.google.com/search?q=KLA+Corporation+careers',
    'Kraft Heinz': 'https://www.google.com/search?q=Kraft+Heinz+careers',
    'Kroger': 'https://www.google.com/search?q=Kroger+careers',
    'L3Harris': 'https://www.google.com/search?q=L3Harris+careers',
    'Labcorp': 'https://www.google.com/search?q=Labcorp+careers',
    'Las Vegas Sands': 'https://www.google.com/search?q=Las+Vegas+Sands+careers',
    'Leidos': 'https://www.google.com/search?q=Leidos+careers',
    'Lennar': 'https://www.google.com/search?q=Lennar+careers',
    'Lennox International': 'https://www.google.com/search?q=Lennox+International+careers',
    'Lilly (Eli)': 'https://www.google.com/search?q=Lilly+%28Eli%29+careers',
    'Linde plc': 'https://www.google.com/search?q=Linde+plc+careers',
    'Live Nation Entertainment': 'https://www.google.com/search?q=Live+Nation+Entertainment+careers',
    'Lockheed Martin': 'https://www.google.com/search?q=Lockheed+Martin+careers',
    'Loews Corporation': 'https://www.google.com/search?q=Loews+Corporation+careers',
    "Lowe's": 'https://www.google.com/search?q=Lowe%27s+careers',
    'Lululemon Athletica': 'https://www.google.com/search?q=Lululemon+Athletica+careers',
    'Lumentum': 'https://www.google.com/search?q=Lumentum+careers',
    'LyondellBasell': 'https://www.google.com/search?q=LyondellBasell+careers',
    'M&T Bank': 'https://www.google.com/search?q=M%26T+Bank+careers',
    'Marathon Petroleum': 'https://www.google.com/search?q=Marathon+Petroleum+careers',
    'Marriott International': 'https://www.google.com/search?q=Marriott+International+careers',
    'Marsh McLennan': 'https://www.google.com/search?q=Marsh+McLennan+careers',
    'Martin Marietta Materials': 'https://www.google.com/search?q=Martin+Marietta+Materials+careers',
    'Marvell Technology': 'https://www.google.com/search?q=Marvell+Technology+careers',
    'Masco': 'https://www.google.com/search?q=Masco+careers',
    'McCormick & Company': 'https://www.google.com/search?q=McCormick+%26+Company+careers',
    "McDonald's": 'https://www.google.com/search?q=McDonald%27s+careers',
    'McKesson Corporation': 'https://www.google.com/search?q=McKesson+Corporation+careers',
    'Merck & Co.': 'https://www.google.com/search?q=Merck+%26+Co.+careers',
    'Meta Platforms': 'https://www.google.com/search?q=Meta+Platforms+careers',
    'MetLife': 'https://www.google.com/search?q=MetLife+careers',
    'Mettler Toledo': 'https://www.google.com/search?q=Mettler+Toledo+careers',
    'MGM Resorts': 'https://www.google.com/search?q=MGM+Resorts+careers',
    'Microchip Technology': 'https://www.google.com/search?q=Microchip+Technology+careers',
    'Micron Technology': 'https://www.google.com/search?q=Micron+Technology+careers',
    'Mid-America Apartment Communities': 'https://www.google.com/search?q=Mid-America+Apartment+Communities+careers',
    'Moderna': 'https://www.google.com/search?q=Moderna+careers',
    'Molson Coors Beverage Company': 'https://www.google.com/search?q=Molson+Coors+Beverage+Company+careers',
    'Mondelez International': 'https://www.google.com/search?q=Mondelez+International+careers',
    'Monolithic Power Systems': 'https://www.google.com/search?q=Monolithic+Power+Systems+careers',
    'Monster Beverage': 'https://www.google.com/search?q=Monster+Beverage+careers',
    "Moody's Corporation": 'https://www.google.com/search?q=Moody%27s+Corporation+careers',
    'Mosaic Company (The)': 'https://www.google.com/search?q=Mosaic+Company+%28The%29+careers',
    'Motorola Solutions': 'https://www.google.com/search?q=Motorola+Solutions+careers',
    'MSCI Inc.': 'https://www.google.com/search?q=MSCI+Inc.+careers',
    'Nasdaq, Inc.': 'https://www.google.com/search?q=Nasdaq%2C+Inc.+careers',
    'Newmont': 'https://www.google.com/search?q=Newmont+careers',
    'News Corp (Class A)': 'https://www.google.com/search?q=News+Corp+%28Class+A%29+careers',
    'News Corp (Class B)': 'https://www.google.com/search?q=News+Corp+%28Class+B%29+careers',
    'NextEra Energy': 'https://www.google.com/search?q=NextEra+Energy+careers',
    'Nike, Inc.': 'https://www.google.com/search?q=Nike%2C+Inc.+careers',
    'NiSource': 'https://www.google.com/search?q=NiSource+careers',
    'Nordson Corporation': 'https://www.google.com/search?q=Nordson+Corporation+careers',
    'Norfolk Southern': 'https://www.google.com/search?q=Norfolk+Southern+careers',
    'Northern Trust': 'https://www.google.com/search?q=Northern+Trust+careers',
    'Northrop Grumman': 'https://www.google.com/search?q=Northrop+Grumman+careers',
    'Norwegian Cruise Line Holdings': 'https://www.google.com/search?q=Norwegian+Cruise+Line+Holdings+careers',
    'NRG Energy': 'https://www.google.com/search?q=NRG+Energy+careers',
    'Nucor': 'https://www.google.com/search?q=Nucor+careers',
    'Nvidia': 'https://www.google.com/search?q=Nvidia+careers',
    'NVR, Inc.': 'https://www.google.com/search?q=NVR%2C+Inc.+careers',
    'NXP Semiconductors': 'https://www.google.com/search?q=NXP+Semiconductors+careers',
    'O\u2019Reilly Automotive': 'https://www.google.com/search?q=O%E2%80%99Reilly+Automotive+careers',
    'Occidental Petroleum': 'https://www.google.com/search?q=Occidental+Petroleum+careers',
    'Old Dominion': 'https://www.google.com/search?q=Old+Dominion+careers',
    'Omnicom Group': 'https://www.google.com/search?q=Omnicom+Group+careers',
    'ON Semiconductor': 'https://www.google.com/search?q=ON+Semiconductor+careers',
    'Oneok': 'https://www.google.com/search?q=Oneok+careers',
    'Oracle Corporation': 'https://www.google.com/search?q=Oracle+Corporation+careers',
    'Otis Worldwide': 'https://www.google.com/search?q=Otis+Worldwide+careers',
    'Paccar': 'https://www.google.com/search?q=Paccar+careers',
    'Packaging Corporation of America': 'https://www.google.com/search?q=Packaging+Corporation+of+America+careers',
    'Palantir Technologies': 'https://www.google.com/search?q=Palantir+Technologies+careers',
    'Paramount Skydance Corporation': 'https://www.google.com/search?q=Paramount+Skydance+Corporation+careers',
    'Parker Hannifin': 'https://www.google.com/search?q=Parker+Hannifin+careers',
    'Paychex': 'https://www.google.com/search?q=Paychex+careers',
    'Pentair': 'https://www.google.com/search?q=Pentair+careers',
    'PepsiCo': 'https://www.google.com/search?q=PepsiCo+careers',
    'PG&E Corporation': 'https://www.google.com/search?q=PG%26E+Corporation+careers',
    'Philip Morris International': 'https://www.google.com/search?q=Philip+Morris+International+careers',
    'Phillips 66': 'https://www.google.com/search?q=Phillips+66+careers',
    'Pinnacle West Capital': 'https://www.google.com/search?q=Pinnacle+West+Capital+careers',
    'PNC Financial Services': 'https://www.google.com/search?q=PNC+Financial+Services+careers',
    'PPG Industries': 'https://www.google.com/search?q=PPG+Industries+careers',
    'PPL Corporation': 'https://www.google.com/search?q=PPL+Corporation+careers',
    'Principal Financial Group': 'https://www.google.com/search?q=Principal+Financial+Group+careers',
    'Procter & Gamble': 'https://www.google.com/search?q=Procter+%26+Gamble+careers',
    'Progressive Corporation': 'https://www.google.com/search?q=Progressive+Corporation+careers',
    'Prologis': 'https://www.google.com/search?q=Prologis+careers',
    'Prudential Financial': 'https://www.google.com/search?q=Prudential+Financial+careers',
    'Public Service Enterprise Group': 'https://www.google.com/search?q=Public+Service+Enterprise+Group+careers',
    'PTC Inc.': 'https://www.google.com/search?q=PTC+Inc.+careers',
    'Public Storage': 'https://www.google.com/search?q=Public+Storage+careers',
    'PulteGroup': 'https://www.google.com/search?q=PulteGroup+careers',
    'Quanta Services': 'https://www.google.com/search?q=Quanta+Services+careers',
    'Quest Diagnostics': 'https://www.google.com/search?q=Quest+Diagnostics+careers',
    'Qnity Electronics': 'https://www.google.com/search?q=Qnity+Electronics+careers',
    'Ralph Lauren Corporation': 'https://www.google.com/search?q=Ralph+Lauren+Corporation+careers',
    'Raymond James Financial': 'https://www.google.com/search?q=Raymond+James+Financial+careers',
    'RTX Corporation': 'https://www.google.com/search?q=RTX+Corporation+careers',
    'Realty Income': 'https://www.google.com/search?q=Realty+Income+careers',
    'Regency Centers': 'https://www.google.com/search?q=Regency+Centers+careers',
    'Regeneron Pharmaceuticals': 'https://www.google.com/search?q=Regeneron+Pharmaceuticals+careers',
    'Regions Financial Corporation': 'https://www.google.com/search?q=Regions+Financial+Corporation+careers',
    'Republic Services': 'https://www.google.com/search?q=Republic+Services+careers',
    'ResMed': 'https://www.google.com/search?q=ResMed+careers',
    'Revvity': 'https://www.google.com/search?q=Revvity+careers',
    'Robinhood Markets': 'https://www.google.com/search?q=Robinhood+Markets+careers',
    'Rollins, Inc.': 'https://www.google.com/search?q=Rollins%2C+Inc.+careers',
    'Roper Technologies': 'https://www.google.com/search?q=Roper+Technologies+careers',
    'Ross Stores': 'https://www.google.com/search?q=Ross+Stores+careers',
    'Royal Caribbean Group': 'https://www.google.com/search?q=Royal+Caribbean+Group+careers',
    'S&P Global': 'https://www.google.com/search?q=S%26P+Global+careers',
    'Sandisk': 'https://www.google.com/search?q=Sandisk+careers',
    'SBA Communications': 'https://www.google.com/search?q=SBA+Communications+careers',
    'Schlumberger': 'https://www.google.com/search?q=Schlumberger+careers',
    'Seagate Technology': 'https://www.google.com/search?q=Seagate+Technology+careers',
    'Sempra': 'https://www.google.com/search?q=Sempra+careers',
    'Sherwin-Williams': 'https://www.google.com/search?q=Sherwin-Williams+careers',
    'Simon Property Group': 'https://www.google.com/search?q=Simon+Property+Group+careers',
    'Skyworks Solutions': 'https://www.google.com/search?q=Skyworks+Solutions+careers',
    'J.M. Smucker Company (The)': 'https://www.google.com/search?q=J.M.+Smucker+Company+%28The%29+careers',
    'Smurfit Westrock': 'https://www.google.com/search?q=Smurfit+Westrock+careers',
    'Snap-on': 'https://www.google.com/search?q=Snap-on+careers',
    'Solventum': 'https://www.google.com/search?q=Solventum+careers',
    'Southern Company': 'https://www.google.com/search?q=Southern+Company+careers',
    'Southwest Airlines': 'https://www.google.com/search?q=Southwest+Airlines+careers',
    'Stanley Black & Decker': 'https://www.google.com/search?q=Stanley+Black+%26+Decker+careers',
    'Starbucks': 'https://www.google.com/search?q=Starbucks+careers',
    'State Street Corporation': 'https://www.google.com/search?q=State+Street+Corporation+careers',
    'Steel Dynamics': 'https://www.google.com/search?q=Steel+Dynamics+careers',
    'Steris': 'https://www.google.com/search?q=Steris+careers',
    'Stryker Corporation': 'https://www.google.com/search?q=Stryker+Corporation+careers',
    'Supermicro': 'https://www.google.com/search?q=Supermicro+careers',
    'Synchrony Financial': 'https://www.google.com/search?q=Synchrony+Financial+careers',
    'Sysco': 'https://www.google.com/search?q=Sysco+careers',
    'T-Mobile US': 'https://www.google.com/search?q=T-Mobile+US+careers',
    'T. Rowe Price': 'https://www.google.com/search?q=T.+Rowe+Price+careers',
    'Take-Two Interactive': 'https://www.google.com/search?q=Take-Two+Interactive+careers',
    'Tapestry, Inc.': 'https://www.google.com/search?q=Tapestry%2C+Inc.+careers',
    'Targa Resources': 'https://www.google.com/search?q=Targa+Resources+careers',
    'Target Corporation': 'https://www.google.com/search?q=Target+Corporation+careers',
    'TE Connectivity': 'https://www.google.com/search?q=TE+Connectivity+careers',
    'Teledyne Technologies': 'https://www.google.com/search?q=Teledyne+Technologies+careers',
    'Teradyne': 'https://www.google.com/search?q=Teradyne+careers',
    'Tesla, Inc.': 'https://www.google.com/search?q=Tesla%2C+Inc.+careers',
    'Texas Pacific Land Corporation': 'https://www.google.com/search?q=Texas+Pacific+Land+Corporation+careers',
    'Textron': 'https://www.google.com/search?q=Textron+careers',
    'TJX Companies': 'https://www.google.com/search?q=TJX+Companies+careers',
    'TKO Group Holdings': 'https://www.google.com/search?q=TKO+Group+Holdings+careers',
    'Trade Desk (The)': 'https://www.google.com/search?q=Trade+Desk+%28The%29+careers',
    'Tractor Supply': 'https://www.google.com/search?q=Tractor+Supply+careers',
    'Trane Technologies': 'https://www.google.com/search?q=Trane+Technologies+careers',
    'TransDigm Group': 'https://www.google.com/search?q=TransDigm+Group+careers',
    'Travelers Companies (The)': 'https://www.google.com/search?q=Travelers+Companies+%28The%29+careers',
    'Trimble Inc.': 'https://www.google.com/search?q=Trimble+Inc.+careers',
    'Truist Financial': 'https://www.google.com/search?q=Truist+Financial+careers',
    'Tyler Technologies': 'https://www.google.com/search?q=Tyler+Technologies+careers',
    'Tyson Foods': 'https://www.google.com/search?q=Tyson+Foods+careers',
    'U.S. Bancorp': 'https://www.google.com/search?q=U.S.+Bancorp+careers',
    'UDR, Inc.': 'https://www.google.com/search?q=UDR%2C+Inc.+careers',
    'Ulta Beauty': 'https://www.google.com/search?q=Ulta+Beauty+careers',
    'Union Pacific Corporation': 'https://www.google.com/search?q=Union+Pacific+Corporation+careers',
    'United Airlines Holdings': 'https://www.google.com/search?q=United+Airlines+Holdings+careers',
    'United Parcel Service': 'https://www.google.com/search?q=United+Parcel+Service+careers',
    'United Rentals': 'https://www.google.com/search?q=United+Rentals+careers',
    'UnitedHealth Group': 'https://www.google.com/search?q=UnitedHealth+Group+careers',
    'Universal Health Services': 'https://www.google.com/search?q=Universal+Health+Services+careers',
    'Valero Energy': 'https://www.google.com/search?q=Valero+Energy+careers',
    'Veeva Systems': 'https://www.google.com/search?q=Veeva+Systems+careers',
    'Ventas': 'https://www.google.com/search?q=Ventas+careers',
    'Veralto': 'https://www.google.com/search?q=Veralto+careers',
    'Verisign': 'https://www.google.com/search?q=Verisign+careers',
    'Verisk Analytics': 'https://www.google.com/search?q=Verisk+Analytics+careers',
    'Verizon': 'https://www.google.com/search?q=Verizon+careers',
    'Vertex Pharmaceuticals': 'https://www.google.com/search?q=Vertex+Pharmaceuticals+careers',
    'Vertiv': 'https://www.google.com/search?q=Vertiv+careers',
    'Viatris': 'https://www.google.com/search?q=Viatris+careers',
    'Vici Properties': 'https://www.google.com/search?q=Vici+Properties+careers',
    'Visa Inc.': 'https://www.google.com/search?q=Visa+Inc.+careers',
    'Vistra Corp .': 'https://www.google.com/search?q=Vistra+Corp+.+careers',
    'Vulcan Materials Company': 'https://www.google.com/search?q=Vulcan+Materials+Company+careers',
    'W. R. Berkley Corporation': 'https://www.google.com/search?q=W.+R.+Berkley+Corporation+careers',
    'W. W. Grainger': 'https://www.google.com/search?q=W.+W.+Grainger+careers',
    'Wabtec': 'https://www.google.com/search?q=Wabtec+careers',
    'Walmart': 'https://www.google.com/search?q=Walmart+careers',
    'Walt Disney Company (The)': 'https://www.google.com/search?q=Walt+Disney+Company+%28The%29+careers',
    'Warner Bros. Discovery': 'https://www.google.com/search?q=Warner+Bros.+Discovery+careers',
    'Waste Management': 'https://www.google.com/search?q=Waste+Management+careers',
    'Waters Corporation': 'https://www.google.com/search?q=Waters+Corporation+careers',
    'WEC Energy Group': 'https://www.google.com/search?q=WEC+Energy+Group+careers',
    'Wells Fargo': 'https://www.google.com/search?q=Wells+Fargo+careers',
    'Welltower': 'https://www.google.com/search?q=Welltower+careers',
    'West Pharmaceutical Services': 'https://www.google.com/search?q=West+Pharmaceutical+Services+careers',
    'Weyerhaeuser': 'https://www.google.com/search?q=Weyerhaeuser+careers',
    'Williams-Sonoma, Inc.': 'https://www.google.com/search?q=Williams-Sonoma%2C+Inc.+careers',
    'Williams Companies': 'https://www.google.com/search?q=Williams+Companies+careers',
    'Willis Towers Watson': 'https://www.google.com/search?q=Willis+Towers+Watson+careers',
    'Workday, Inc.': 'https://www.google.com/search?q=Workday%2C+Inc.+careers',
    'Wynn Resorts': 'https://www.google.com/search?q=Wynn+Resorts+careers',
    'Xcel Energy': 'https://www.google.com/search?q=Xcel+Energy+careers',
    'Xylem Inc.': 'https://www.google.com/search?q=Xylem+Inc.+careers',
    'Yum! Brands': 'https://www.google.com/search?q=Yum%21+Brands+careers',
    'Zebra Technologies': 'https://www.google.com/search?q=Zebra+Technologies+careers',
    'Zimmer Biomet': 'https://www.google.com/search?q=Zimmer+Biomet+careers',
    'Zoetis': 'https://www.google.com/search?q=Zoetis+careers',
    'ASML Holding': 'https://www.google.com/search?q=ASML+Holding+careers',
    'Taiwan Semiconductor Manufacturing Company': 'https://www.google.com/search?q=Taiwan+Semiconductor+Manufacturing+Company+careers',
    'Samsung Electronics': 'https://www.google.com/search?q=Samsung+Electronics+careers',
    'Sony Group': 'https://www.google.com/search?q=Sony+Group+careers',
    'Nintendo': 'https://www.google.com/search?q=Nintendo+careers',
    'Toyota Motor Corporation': 'https://www.google.com/search?q=Toyota+Motor+Corporation+careers',
    'Honda Motor Company': 'https://www.google.com/search?q=Honda+Motor+Company+careers',
    'Hyundai Motor Company': 'https://www.google.com/search?q=Hyundai+Motor+Company+careers',
    'Kia Corporation': 'https://www.google.com/search?q=Kia+Corporation+careers',
    'LG Electronics': 'https://www.google.com/search?q=LG+Electronics+careers',
    'SK Hynix': 'https://www.google.com/search?q=SK+Hynix+careers',
    'Panasonic Holdings': 'https://www.google.com/search?q=Panasonic+Holdings+careers',
    'Canon': 'https://www.google.com/search?q=Canon+careers',
    'Fujitsu': 'https://www.google.com/search?q=Fujitsu+careers',
    'NEC Corporation': 'https://www.google.com/search?q=NEC+Corporation+careers',
    'Toshiba': 'https://www.google.com/search?q=Toshiba+careers',
    'Hitachi Ltd.': 'https://www.google.com/search?q=Hitachi+Ltd.+careers',
    'Mitsubishi Electric': 'https://www.google.com/search?q=Mitsubishi+Electric+careers',
    'Schindler Group': 'https://www.google.com/search?q=Schindler+Group+careers',
    'ABB Ltd.': 'https://www.google.com/search?q=ABB+Ltd.+careers',
    'STMicroelectronics': 'https://www.google.com/search?q=STMicroelectronics+careers',
    'Infineon Technologies': 'https://www.google.com/search?q=Infineon+Technologies+careers',
    'ASM International': 'https://www.google.com/search?q=ASM+International+careers',
    'BE Semiconductor Industries': 'https://www.google.com/search?q=BE+Semiconductor+Industries+careers',
    'Tokyo Electron': 'https://www.google.com/search?q=Tokyo+Electron+careers',
    'Disco Corporation': 'https://www.google.com/search?q=Disco+Corporation+careers',
    'Advantest': 'https://www.google.com/search?q=Advantest+careers',
    'Renesas Electronics': 'https://www.google.com/search?q=Renesas+Electronics+careers',
    'MediaTek': 'https://www.google.com/search?q=MediaTek+careers',
    'Tencent': 'https://www.google.com/search?q=Tencent+careers',
    'Alibaba Group Holding': 'https://www.google.com/search?q=Alibaba+Group+Holding+careers',
    'Baidu': 'https://www.google.com/search?q=Baidu+careers',
    'JD.com': 'https://www.google.com/search?q=JD.com+careers',
    'NetEase': 'https://www.google.com/search?q=NetEase+careers',
    'Meituan': 'https://www.google.com/search?q=Meituan+careers',
    'Mercado Libre': 'https://www.google.com/search?q=Mercado+Libre+careers',
    'Shopify': 'https://www.google.com/search?q=Shopify+careers',
    'Spotify': 'https://www.google.com/search?q=Spotify+careers',
    'Yandex': 'https://www.google.com/search?q=Yandex+careers',
    'Rakuten Group': 'https://www.google.com/search?q=Rakuten+Group+careers',
    'Naver': 'https://www.google.com/search?q=Naver+careers',
    'Kakao': 'https://www.google.com/search?q=Kakao+careers',
    'Sea Limited Ltd.': 'https://www.google.com/search?q=Sea+Limited+Ltd.+careers',
}

# Additional established global product employers with direct official career
# pages. These are deliberately not search-engine discovery placeholders.
NON_STARTUP_PRODUCT_COMPANY_CAREER_PAGE_URLS.update({
    "Xiaomi": "https://career.mi.com/jobs",
    "Dassault Systemes": "https://www.3ds.com/careers",
    "Airbus": "https://www.airbus.com/en/careers",
    "Rolls-Royce": "https://careers.rolls-royce.com/en",
    "SUSE": "https://www.suse.com/careers/",
    "Seagate": "https://seagatecareers.com/",
    "Temenos": "https://www.temenos.com/about-us/careers/",
    "Finastra": "https://www.finastra.com/careers/life-at-finastra",
    "SAS": "https://www.sas.com/en_us/careers.html",
    "Unity": "https://unity.com/careers",
    "Ubisoft": "https://www.ubisoft.com/en-us/company/careers",
    "Epic Games": "https://www.epicgames.com/site/en-US/careers",
    "GSK": "https://jobs.gsk.com/",
    "Novo Nordisk": "https://www.novonordisk.com/careers.html",
    "Zoom Video Communications": "https://careers.zoom.us/",
    "Check Point Software": "https://careers.checkpoint.com/",
    "F5": "https://www.f5.com/company/careers",
    "OpenText": "https://careers.opentext.com/us/en",
    "NICE": "https://www.nice.com/careers",
    "Amdocs": "https://www.amdocs.com/careers/home",
    "Pegasystems": "https://www.pega.com/about/careers",
    "Guidewire Software": "https://www.guidewire.com/about/careers",
    "Commvault": "https://careers.commvault.com/us/en",
    "Progress Software": "https://www.progress.com/company/careers",
    "SolarWinds": "https://careers.solarwinds.com/",
    "Teradata": "https://careers.teradata.com/jobs",
    "Tally Solutions": "https://tallysolutions.com/careers/",
    "Xero": "https://careers.xero.com/",
    "WiseTech Global": "https://www.wisetechglobal.com/careers/join-us/",
    "TechnologyOne": "https://www.technologyonecorp.com/company/careers",
    "MYOB": "https://careers.myob.com/",
    "REA Group": "https://www.rea-group.com/careers/",
    "Thales": "https://careers.thalesgroup.com/global/en",
    "Safran": "https://www.safran-group.com/jobs",
    "BAE Systems": "https://jobs.baesystems.com/global/en",
    "Continental": "https://jobs.continental.com/en/",
    "ZF Friedrichshafen": "https://jobs.zf.com/",
    "Michelin": "https://jobs.michelin.com/",
    "Bridgestone": "https://www.bridgestoneamericas.com/en/our-team",
    "Air Liquide": "https://www.airliquide.com/join-us/careers-air-liquide",
    "Nestle": "https://www.nestle.com/jobs",
    "Unilever": "https://careers.unilever.com/en",
    "LVMH": "https://www.lvmh.com/join-us/our-job-offers",
    "Sony Interactive Entertainment": "https://careers.playstation.com/",
})
