#!/usr/bin/env python3
"""
Cross-platform local setup for Job Scraper and the optional Next.js web UI.

Run from the backend repo:
  python scripts/local_setup.py

What it does:
  - creates/updates .venv
  - installs Python requirements
  - installs Playwright Chromium
  - creates local env files from existing sibling env/template data
  - installs the sibling jobs-scraper-web dependencies when present
  - writes APPLICATION_ASSISTANT_DIR / APPLICATION_ASSISTANT_PYTHON for the UI
"""

from __future__ import annotations

import argparse
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path


BACKEND_ENV_KEYS = [
    "SUPABASE_URL",
    "SUPABASE_SERVICE_ROLE_KEY",
    "GEMINI_API_KEY",
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "GROQ_API_KEY",
    "LINKEDIN_STORAGE_STATE_JSON",
    "NAUKRI_STORAGE_STATE_JSON",
    "NAUKRI_GULF_STORAGE_STATE_JSON",
    "APPLICATION_DEFAULT_ANSWERS_JSON",
    "APPLICATION_PORTAL_EMAIL",
    "APPLICATION_PORTAL_PASSWORD",
    "JOB_ALERT_EMAIL_TO",
    "JOB_ALERT_EMAIL_FROM",
    "SMTP_HOST",
    "SMTP_PORT",
    "SMTP_USERNAME",
    "SMTP_PASSWORD",
]

FRONTEND_ENV_KEYS = [
    "NEXT_PUBLIC_SUPABASE_URL",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY",
    "NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY",
    "GEMINI_API_KEY",
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "GROQ_API_KEY",
    "LINKEDIN_STORAGE_STATE_JSON",
    "APPLICATION_DEFAULT_ANSWERS_JSON",
    "APPLICATION_PORTAL_EMAIL",
    "APPLICATION_PORTAL_PASSWORD",
    "APPLICATION_ASSISTANT_DIR",
    "APPLICATION_ASSISTANT_PYTHON",
    "JOBTRACK_LIVE_HEADLESS",
]


def log(message: str) -> None:
    print(f"[setup] {message}", flush=True)


def command_exists(command: str) -> bool:
    return shutil.which(command) is not None


def run(command: list[str], cwd: Path, check: bool = True) -> subprocess.CompletedProcess:
    log(f"{cwd}> {' '.join(command)}")
    return subprocess.run(command, cwd=str(cwd), check=check)


def run_if_available(command: list[str], cwd: Path) -> bool:
    try:
        run(command, cwd=cwd)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        log(f"Command failed or is unavailable: {' '.join(command)} ({exc})")
        return False


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def venv_python(backend_dir: Path) -> Path:
    if platform.system().lower().startswith("win"):
        return backend_dir / ".venv" / "Scripts" / "python.exe"
    return backend_dir / ".venv" / "bin" / "python"


def parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            values[key] = value
    return values


def process_env_values(keys: list[str]) -> dict[str, str]:
    return {
        key: value
        for key in keys
        if (value := os.environ.get(key, "").strip())
    }


def write_env_file(path: Path, values: dict[str, str], keys: list[str]) -> None:
    lines = [
        "# Generated by scripts/local_setup.py",
        "# Fill missing values, then rerun setup if needed.",
        "",
    ]
    for key in keys:
        value = values.get(key, "")
        if value:
            lines.append(f'{key}="{value}"')
        else:
            lines.append(f"{key}=")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def merge_backend_env(backend_env: dict[str, str], frontend_env: dict[str, str]) -> dict[str, str]:
    merged = dict(backend_env)
    if not merged.get("SUPABASE_URL") and frontend_env.get("NEXT_PUBLIC_SUPABASE_URL"):
        merged["SUPABASE_URL"] = frontend_env["NEXT_PUBLIC_SUPABASE_URL"]
    if not merged.get("SUPABASE_SERVICE_ROLE_KEY") and frontend_env.get("NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY"):
        merged["SUPABASE_SERVICE_ROLE_KEY"] = frontend_env["NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY"]
    for key in BACKEND_ENV_KEYS:
        if not merged.get(key) and frontend_env.get(key):
            merged[key] = frontend_env[key]
    return merged


def merge_frontend_env(frontend_env: dict[str, str], backend_env: dict[str, str], backend_dir: Path) -> dict[str, str]:
    merged = dict(frontend_env)
    if not merged.get("NEXT_PUBLIC_SUPABASE_URL") and backend_env.get("SUPABASE_URL"):
        merged["NEXT_PUBLIC_SUPABASE_URL"] = backend_env["SUPABASE_URL"]
    if not merged.get("NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY") and backend_env.get("SUPABASE_SERVICE_ROLE_KEY"):
        merged["NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY"] = backend_env["SUPABASE_SERVICE_ROLE_KEY"]
    for key in ("GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY", "GROQ_API_KEY"):
        if not merged.get(key) and backend_env.get(key):
            merged[key] = backend_env[key]
    for key in ("LINKEDIN_STORAGE_STATE_JSON", "APPLICATION_DEFAULT_ANSWERS_JSON", "APPLICATION_PORTAL_EMAIL", "APPLICATION_PORTAL_PASSWORD"):
        if not merged.get(key) and backend_env.get(key):
            merged[key] = backend_env[key]
    merged["APPLICATION_ASSISTANT_DIR"] = str(backend_dir)
    merged["APPLICATION_ASSISTANT_PYTHON"] = str(venv_python(backend_dir))
    merged.setdefault("JOBTRACK_LIVE_HEADLESS", "1")
    return merged


def ensure_backend_env(backend_dir: Path, frontend_dir: Path | None, force: bool) -> None:
    backend_env_path = backend_dir / ".env"
    frontend_env_path = frontend_dir / ".env.local" if frontend_dir else None
    backend_env = {
        **process_env_values(BACKEND_ENV_KEYS),
        **parse_env_file(backend_env_path),
    }
    frontend_env = {
        **process_env_values(FRONTEND_ENV_KEYS),
        **(parse_env_file(frontend_env_path) if frontend_env_path else {}),
    }

    if backend_env_path.exists() and not force:
        log(".env already exists; preserving it.")
        return

    merged = merge_backend_env(backend_env, frontend_env)
    write_env_file(backend_env_path, merged, BACKEND_ENV_KEYS)
    log(f"Wrote {backend_env_path}")


def ensure_frontend_env(backend_dir: Path, frontend_dir: Path, force: bool) -> None:
    frontend_env_path = frontend_dir / ".env.local"
    backend_env = {
        **process_env_values(BACKEND_ENV_KEYS),
        **parse_env_file(backend_dir / ".env"),
    }
    frontend_env = {
        **process_env_values(FRONTEND_ENV_KEYS),
        **parse_env_file(frontend_env_path),
    }

    if frontend_env_path.exists() and not force:
        merged = merge_frontend_env(frontend_env, backend_env, backend_dir)
        write_env_file(frontend_env_path, merged, FRONTEND_ENV_KEYS)
        log(".env.local already existed; updated assistant paths and preserved known values.")
        return

    merged = merge_frontend_env(frontend_env, backend_env, backend_dir)
    write_env_file(frontend_env_path, merged, FRONTEND_ENV_KEYS)
    log(f"Wrote {frontend_env_path}")


def find_frontend_dir(backend_dir: Path, requested: str | None) -> Path | None:
    candidates = []
    if requested:
        candidates.append(Path(requested).expanduser())
    candidates.extend(
        [
            backend_dir.parent / "jobs-scraper-web",
            backend_dir / "jobs-scraper-web",
            backend_dir.parent / "jobs-scrapper-web",
            backend_dir / "jobs-scrapper-web",
        ]
    )
    for candidate in candidates:
        candidate = candidate.resolve()
        if (candidate / "package.json").exists():
            return candidate
    return None


def ensure_python_venv(backend_dir: Path) -> Path:
    python_path = venv_python(backend_dir)
    if not python_path.exists():
        run([sys.executable, "-m", "venv", ".venv"], cwd=backend_dir)
    else:
        log(f"Using existing venv: {python_path}")
    return python_path


def install_python_dependencies(backend_dir: Path, python_path: Path, skip_playwright: bool) -> None:
    run([str(python_path), "-m", "pip", "install", "--upgrade", "pip"], cwd=backend_dir)
    run([str(python_path), "-m", "pip", "install", "-r", "requirements.txt"], cwd=backend_dir)
    if not skip_playwright:
        run([str(python_path), "-m", "playwright", "install", "chromium"], cwd=backend_dir)


def install_frontend_dependencies(frontend_dir: Path) -> None:
    ensure_nodejs(frontend_dir)
    npm = shutil.which("npm.cmd") or shutil.which("npm")
    if not npm:
        raise RuntimeError("npm was not found after install attempt. Install Node.js 20+ and rerun setup.")
    if (frontend_dir / "package-lock.json").exists():
        run([npm, "ci"], cwd=frontend_dir)
    else:
        run([npm, "install"], cwd=frontend_dir)


def ensure_nodejs(cwd: Path) -> None:
    npm = shutil.which("npm.cmd") or shutil.which("npm")
    node = shutil.which("node.exe") or shutil.which("node")
    if node and npm:
        version = subprocess.run([node, "--version"], capture_output=True, text=True, check=False)
        version_text = (version.stdout or "").strip()
        major = parse_node_major(version_text)
        if major and major >= 20:
            log(f"Node.js already installed: {version_text}")
            return
        log(f"Node.js is missing or too old ({version_text or node}). Trying automatic install/upgrade.")
    else:
        log("Node.js/npm not found. Trying automatic install.")

    system = platform.system().lower()

    if system.startswith("win"):
        if command_exists("winget"):
            run(["winget", "install", "--id", "OpenJS.NodeJS.LTS", "-e", "--accept-package-agreements", "--accept-source-agreements"], cwd=cwd)
            return
        if command_exists("choco"):
            run(["choco", "install", "nodejs-lts", "-y"], cwd=cwd)
            return
        raise RuntimeError("Node.js/npm is missing and neither winget nor choco is available.")

    if system == "darwin":
        if command_exists("brew"):
            run(["brew", "install", "node"], cwd=cwd)
            return
        raise RuntimeError("Node.js/npm is missing and Homebrew is not available.")

    if command_exists("apt-get"):
        if os.geteuid() == 0:
            run(["apt-get", "update"], cwd=cwd)
            run(["apt-get", "install", "-y", "nodejs", "npm"], cwd=cwd)
        elif command_exists("sudo"):
            run(["sudo", "apt-get", "update"], cwd=cwd)
            run(["sudo", "apt-get", "install", "-y", "nodejs", "npm"], cwd=cwd)
        else:
            raise RuntimeError("Node.js/npm is missing and sudo is not available for apt-get.")
        return

    if command_exists("dnf"):
        command = ["dnf", "install", "-y", "nodejs", "npm"] if os.geteuid() == 0 else ["sudo", "dnf", "install", "-y", "nodejs", "npm"]
        run(command, cwd=cwd)
        return

    if command_exists("yum"):
        command = ["yum", "install", "-y", "nodejs", "npm"] if os.geteuid() == 0 else ["sudo", "yum", "install", "-y", "nodejs", "npm"]
        run(command, cwd=cwd)
        return

    if command_exists("pacman"):
        command = ["pacman", "-Sy", "--noconfirm", "nodejs", "npm"] if os.geteuid() == 0 else ["sudo", "pacman", "-Sy", "--noconfirm", "nodejs", "npm"]
        run(command, cwd=cwd)
        return

    raise RuntimeError("Node.js/npm is missing and no supported package manager was found.")


def parse_node_major(version_text: str) -> int | None:
    version_text = version_text.strip().lstrip("v")
    major_text = version_text.split(".", 1)[0]
    try:
        return int(major_text)
    except ValueError:
        return None


def write_helper_scripts(backend_dir: Path, frontend_dir: Path | None) -> None:
    scripts_dir = backend_dir / "scripts"
    scripts_dir.mkdir(exist_ok=True)

    py = venv_python(backend_dir)
    run_backend = scripts_dir / ("run-backend-command.ps1" if platform.system().lower().startswith("win") else "run-backend-command.sh")
    if platform.system().lower().startswith("win"):
        run_backend.write_text(
            f'$ErrorActionPreference = "Stop"\n& "{py}" $args\n',
            encoding="utf-8",
        )
    else:
        run_backend.write_text(
            f'#!/usr/bin/env bash\nset -euo pipefail\n"{py}" "$@"\n',
            encoding="utf-8",
        )
        run_backend.chmod(0o755)

    if frontend_dir:
        run_web = scripts_dir / ("run-web.ps1" if platform.system().lower().startswith("win") else "run-web.sh")
        if platform.system().lower().startswith("win"):
            run_web.write_text(
                f'$ErrorActionPreference = "Stop"\nSet-Location "{frontend_dir}"\nnpm run dev -- --hostname 0.0.0.0 --port 3000\n',
                encoding="utf-8",
            )
        else:
            run_web.write_text(
                f'#!/usr/bin/env bash\nset -euo pipefail\ncd "{frontend_dir}"\nnpm run dev -- --hostname 0.0.0.0 --port 3000\n',
                encoding="utf-8",
            )
            run_web.chmod(0o755)
    write_port_forward_helper(scripts_dir)
    log("Wrote local helper run scripts under scripts/.")


def write_port_forward_helper(scripts_dir: Path) -> None:
    if platform.system().lower().startswith("win"):
        helper = scripts_dir / "enable-port-forward-3000.ps1"
        helper.write_text(
            """param(
  [string]$ListenAddress = "0.0.0.0",
  [string]$ConnectAddress = "127.0.0.1",
  [int]$Port = 3000
)

$ErrorActionPreference = "Stop"

$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)
if (-not $isAdmin) {
  Write-Error "Run this PowerShell as Administrator to configure Windows portproxy/firewall."
}

netsh interface portproxy delete v4tov4 listenaddress=$ListenAddress listenport=$Port 2>$null | Out-Null
netsh interface portproxy add v4tov4 listenaddress=$ListenAddress listenport=$Port connectaddress=$ConnectAddress connectport=$Port

$ruleName = "JobTrack Web Port $Port"
if (-not (Get-NetFirewallRule -DisplayName $ruleName -ErrorAction SilentlyContinue)) {
  New-NetFirewallRule -DisplayName $ruleName -Direction Inbound -Action Allow -Protocol TCP -LocalPort $Port | Out-Null
}

Write-Host "Port forwarding enabled: $ListenAddress`:$Port -> $ConnectAddress`:$Port"
Write-Host "Start the web UI with scripts\\run-web.ps1 or npm run dev -- --hostname 0.0.0.0 --port $Port"
""",
            encoding="utf-8",
        )
    else:
        helper = scripts_dir / "enable-port-forward-3000.sh"
        helper.write_text(
            """#!/usr/bin/env bash
set -euo pipefail

PORT="${1:-3000}"

echo "On macOS/Linux the web app normally only needs to bind to 0.0.0.0:"
echo "  npm run dev -- --hostname 0.0.0.0 --port ${PORT}"
echo
echo "If a local firewall is blocking it, open TCP ${PORT} with your OS firewall tool."
echo "Examples:"
echo "  Ubuntu ufw: sudo ufw allow ${PORT}/tcp"
echo "  firewalld:  sudo firewall-cmd --add-port=${PORT}/tcp --permanent && sudo firewall-cmd --reload"
""",
            encoding="utf-8",
        )
        helper.chmod(0o755)


def print_summary(backend_dir: Path, frontend_dir: Path | None, python_path: Path) -> None:
    print("\nLocal setup complete.")
    print(f"Backend: {backend_dir}")
    print(f"Python:  {python_path}")
    if frontend_dir:
        print(f"Web UI:  {frontend_dir}")
        print("Run web UI: npm run dev -- --hostname 0.0.0.0 --port 3000")
        print("Optional LAN/WSL port helper: scripts/enable-port-forward-3000.*")
    print("\nIf .env/.env.local has blank values, fill them once and rerun setup.")
    print("GitHub Actions secrets are write-only and cannot be downloaded to local setup.")
    print("If you export env vars before running setup, they will be copied into .env/.env.local.")
    print("Backend examples: python scraper.py, python score_jobs.py, python job_manager.py")


def install_systemd_service(backend_dir: Path) -> None:
    system = platform.system().lower()
    if system.startswith("linux"):
        installer = backend_dir / "scripts" / "install-systemd-user-service.sh"
        if not installer.exists():
            raise RuntimeError(f"Systemd installer not found: {installer}")
        installer.chmod(0o755)
        run([str(installer)], cwd=backend_dir)
        return

    if system.startswith("win"):
        powershell = shutil.which("powershell.exe") or shutil.which("powershell")
        wsl = shutil.which("wsl.exe") or shutil.which("wsl")
        installer = backend_dir / "setup-systemd.ps1"
        if not powershell or not wsl:
            raise RuntimeError("Automatic systemd install on Windows requires PowerShell and WSL.")
        if not installer.exists():
            raise RuntimeError(f"WSL systemd installer not found: {installer}")
        run([powershell, "-ExecutionPolicy", "Bypass", "-File", str(installer)], cwd=backend_dir)
        return

    raise RuntimeError("systemd service installation is supported only on Linux/WSL.")


def verify_local_setup(backend_dir: Path, frontend_dir: Path | None) -> int:
    failures = 0

    def check(label: str, ok: bool, detail: str = "") -> None:
        nonlocal failures
        status = "OK" if ok else "FAIL"
        print(f"[{status}] {label}{': ' + detail if detail else ''}")
        if not ok:
            failures += 1

    python_path = venv_python(backend_dir)
    check("backend venv python", python_path.exists(), str(python_path))

    if python_path.exists():
        result = subprocess.run(
            [str(python_path), "-c", "import requests, bs4, dotenv, supabase, playwright, reportlab; print('imports ok')"],
            cwd=str(backend_dir),
            capture_output=True,
            text=True,
        )
        check("backend Python dependencies", result.returncode == 0, (result.stdout or result.stderr).strip())

    check("backend .env exists", (backend_dir / ".env").exists(), str(backend_dir / ".env"))

    local_node_dir = Path.home() / ".local" / "jobtrack-node20" / "bin"
    if platform.system().lower().startswith("linux") and (local_node_dir / "node").exists():
        os.environ["PATH"] = f"{local_node_dir}{os.pathsep}{os.environ.get('PATH', '')}"

    node = shutil.which("node") or shutil.which("node.exe")
    npm = shutil.which("npm") or shutil.which("npm.cmd")
    check("node command", bool(node), node or "missing")
    check("npm command", bool(npm), npm or "missing")
    if node:
        version = subprocess.run([node, "--version"], capture_output=True, text=True, check=False)
        major = parse_node_major(version.stdout or "")
        check("Node.js version >= 20", bool(major and major >= 20), (version.stdout or "").strip())

    if frontend_dir:
        check("frontend package.json", (frontend_dir / "package.json").exists(), str(frontend_dir / "package.json"))
        check("frontend node_modules", (frontend_dir / "node_modules").exists(), str(frontend_dir / "node_modules"))
        check("frontend .env.local exists", (frontend_dir / ".env.local").exists(), str(frontend_dir / ".env.local"))
    else:
        check("frontend repo detected", False, "jobs-scraper-web not found")

    if failures:
        print(f"\nLocal setup verification failed: {failures} issue(s).")
        return 1

    print("\nLocal setup verification passed.")
    return 0


def main() -> int:
    if sys.version_info < (3, 11):
        raise RuntimeError(
            f"Python 3.11+ is required, but this interpreter is {sys.version.split()[0]}. "
            "Run setup.ps1/setup.sh so it can try to install a supported Python."
        )

    parser = argparse.ArgumentParser(description="Set up Job Scraper locally on Windows, macOS, or Linux.")
    parser.add_argument("--frontend-dir", help="Path to jobs-scraper-web. Auto-detected when omitted.")
    parser.add_argument("--skip-frontend", action="store_true", help="Do not install or configure the web UI.")
    parser.add_argument("--skip-playwright", action="store_true", help="Skip Playwright browser install.")
    parser.add_argument("--force-env", action="store_true", help="Rewrite .env and .env.local from available values/templates.")
    parser.add_argument("--install-systemd", action="store_true", help="Install/start the JobTrack web systemd user service after setup.")
    parser.add_argument("--verify-only", action="store_true", help="Check local setup without installing/updating dependencies.")
    args = parser.parse_args()

    backend_dir = repo_root()
    frontend_dir = None if args.skip_frontend else find_frontend_dir(backend_dir, args.frontend_dir)

    if args.verify_only:
        return verify_local_setup(backend_dir, frontend_dir)

    ensure_backend_env(backend_dir, frontend_dir, args.force_env)
    python_path = ensure_python_venv(backend_dir)
    install_python_dependencies(backend_dir, python_path, args.skip_playwright)

    if frontend_dir:
        ensure_frontend_env(backend_dir, frontend_dir, args.force_env)
        install_frontend_dependencies(frontend_dir)
    else:
        log("Web UI repo was not found; backend setup completed.")

    write_helper_scripts(backend_dir, frontend_dir)
    if args.install_systemd:
        install_systemd_service(backend_dir)
    print_summary(backend_dir, frontend_dir, python_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
